apiVersion: apps/v1
kind: Deployment
metadata:
  name: rf-dashboard
  namespace: rf-dashboard-demo
  labels:
    app: rf-dashboard
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rf-dashboard
  template:
    metadata:
      labels:
        app: rf-dashboard
    spec:
      containers:
      - name: rf-dashboard
        image: grafana/grafana-oss
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rf-dashboard
  namespace: rf-dashboard-demo
spec:
  type: NodePort
  selector:
    app: rf-dashboard
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31300
