{
 "title": "TestDashboard",
 "time": { "from": "now-30d", "to": "now+1d" },
 "templating": {
  "list": [
   {
    "name": "buildnr",
    "label": "Builds",
    "query": "select distinct build_id from test_series_mapping tsm "
   }
  ]
 },
 "panels": [
  { "title": "Huidige Build", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pass/Fail",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(status) as PASS from \n(select s.status from test_result s\njoin test_series_mapping m on m.test_run_id = s.test_run_id\njoin test_series ts on ts.id = m.series\nwhere status = 'PASS' and m.build_id = '${buildnr}' ) AS derived_table"
    },
    {
     "rawSql": "select count(status) as FAIL from \n(select s.status from test_result s\njoin test_series_mapping m on m.test_run_id = s.test_run_id\njoin test_series ts on ts.id = m.series\nwhere status = 'FAIL' and m.build_id = '${buildnr}' ) AS derived_table"
    }
   ]
  },
  {
   "title": "Doorlooptijd",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT SUM(sr.elapsed), tr.generated as \"time\"\nFROM test_series_mapping tsm\n    JOIN test_run tr ON tsm.test_run_id = tr.id\n    JOIN suite_result sr ON tr.id = sr.test_run_id\nGROUP BY tr.generated"
    }
   ]
  },
  {
   "title": "Error Messages",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT s.name as TestSuite, tc.name as TestCase, lm.message as LogMessage\nFROM test_series_mapping tsm\nJOIN test_run tr ON tsm.test_run_id = tr.id\nJOIN test_result tres ON tr.id = tres.test_run_id\nJOIN test_case tc ON tres.test_id = tc.id \nJOIN suite s ON tc.suite_id = s.id\nJOIN log_message lm ON tres.test_id = lm.test_id AND tsm.test_run_id = lm.test_run_id\nWHERE \n               tres.status = 'FAIL' and \n               tsm.build_id = '${buildnr}' and\n               lm.log_level = 'FAIL'\n"
    }
   ]
  },
  { "title": "Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Trend Pass/Fail",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(generated,$__interval),\n  count(tres.status) AS \"PASS\"\nFROM test_run tr\n    JOIN test_result tres ON tr.id = tres.test_run_id \n    JOIN test_case tc ON tres.test_id = tc.id\nWHERE\n  $__timeFilter(generated) AND\n  tres.status = 'PASS'  \nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(generated,$__interval),\n  count(tres.status) AS \"FAIL\"\nFROM test_run tr\n    JOIN test_result tres ON tr.id = tres.test_run_id \n    JOIN test_case tc ON tres.test_id = tc.id\nWHERE\n  $__timeFilter(generated) AND\n  tres.status = 'FAIL'  \nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Flakyness",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT * \nFROM crosstab('SELECT tc.full_name, trus.test_run_id, execution_status\nFROM test_result trus \nJOIN test_series_mapping tsm ON trus.test_run_id = tsm.test_run_id\nJOIN test_run trun ON trus.test_run_id = trun.id\nJOIN test_case tc ON trus.test_id = tc.id\nWHERE tsm.series = 1 AND trus.test_run_id > (SELECT MAX(test_run_id) FROM test_result)-10\norder by 1,2\n')\n  AS final_result(TestName text, a text, b text, c text, d text, e text, f text, g text, h text, i text, j text);\n"
    }
   ]
  }
 ]
}